---
title: Spatial Analysis of Watersheds
author: ''
date: '2020-01-09'
slug: hawaii_spatial
categories: []
tags:
  - spatial
  - water
subtitle: 'Spatial analysis of land use types on the island of Kauai by watershed'
summary: 'Mapping land use type on Kauai by watershed'
authors: []
lastmod: '2020-01-09T15:02:28-08:00'
featured: no
image:
  caption: 'Associated Press'
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```



```{r}
## Attach packages:
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(paletteer)
library(sf)
library(tmap)
library(mapview)
library(tmaptools)
library(rmapshaper)
```

```{r}
# Read in the shapefiles and check projections

watersheds <- read_sf(dsn = ".",
                 layer = "Watersheds") %>% 
              st_transform(crs = 4326) %>% 
  select("wuname", "area_sqmi")

land_cover <- read_sf(dsn = ".",
                       layer = "Land_Use_Land_Cover_LULC") %>% 
  st_transform(crs = 4326) %>% 
  filter(landcover != 0)

# there are a lot of different land cover types, group into overall categories

land_cover_simple <- land_cover %>% 
  mutate(landcover_type = case_when(
     landcover == "Cropland and Pasture" ~ "Agriculture",
     landcover == "Commercial and Services" ~ "Developed",
     landcover == "Residential" ~ "Developed",          
     landcover =="Evergreen Forest Land" ~ "Natural",   
     landcover =="Other Urban or Built-up Land" ~ "Developed",
     landcover =="Mixed Rangeland" ~ "Agriculture",           
     landcover =="Industrial" ~ "Industrial",                    
     landcover =="Streams and Canals" ~ "Natural",      
     landcover =="Orchards, Groves, Vineyards, Nurseries and Ornamental Horticultural Areas" ~ "Agriculture",
     landcover =="Shrub and Brush Rangeland" ~ "Agriculture",
     landcover =="Forested Wetland" ~ "Natural",        
     landcover =="Reservoirs" ~ "Water",                
     landcover =="Nonforested Wetland" ~ "Natural",     
     landcover =="Bare Exposed Rock" ~ "Natural",       
     landcover =="Sandy Areas Other than Beaches" ~ "Natural",
     landcover =="Transportation, Communications and Utilities" ~ "Industrial",
     landcover =="Herbaceous Rangeland" ~ "Agriculture",
     landcover =="Beaches" ~ "Natural",                 
     landcover =="Other Agricultural Land" ~ "Agriculture",
     landcover =="Lakes" ~ "Water",                     
     landcover =="Strip Mines, Quarries, and Gravel Pits" ~ "Industrial",
     landcover =="Mixed Barren Land" ~ "Natural",       
     landcover =="Bays and Estuaries" ~ "Water",        
     landcover =="Mixed Urban or Built-up Land" ~ "Developed",
     landcover =="Transitional Areas" ~ "Developed",    
     landcover =="Industrial and Commercial Complexes" ~ "Industrial",  
     landcover =="Confined Feeding Operations" ~ "Agriculture"
  )) %>% 
  select(landcover_type)
```

```{r}
#plot(watersheds)
#plot(land_cover_simple)
```

```{r}
hi_map_kauai <- ggplot() +
  geom_sf(data = land_cover_simple,
          aes(fill = landcover_type),
          color = NA) +
  scale_fill_manual(values = c("peru", "darkolivegreen", "grey65", "indianred4", "cadetblue4")) +
  geom_sf(data = watersheds, fill = NA, color = 
            "white", size = 0.2) +
  coord_sf(xlim = c(-159.2, -159.8), ylim = c(21.8, 22.3), expand = FALSE) +
  theme_minimal() +
  labs(fill = "Landcover Type")

hi_map_kauai

```

**Data Sources:**
Land use/land cover data: http://geoportal.hawaii.gov/datasets/land-use-land-cover-lulc

Watershed data: http://geoportal.hawaii.gov/datasets/watersheds